import React from 'react';
import { ArrowLeft, FileText, Gavel, Mail, Phone, Scale } from 'lucide-react';

interface TermsConditionsPageProps {
  onNavigate: (path: string) => void;
}

interface Section {
  heading: string;
  paragraph?: string;
  bullets?: string[];
}

const SECTIONS: Section[] = [
  {
    heading: '1. General Overview & Scope',
    paragraph:
      'In accordance with the Information Technology Act, 2000 and applicable rules, this document is an electronic record generated by a computer system and does not require physical or digital signatures.',
    bullets: [
      'Platform Role: Drishti Fashions serves as an online e-commerce platform connecting buyers and independent brands/sellers. We curate a premium collection of fashion wear while commercial terms (pricing, delivery, warranties) are fulfilled independently.',
      'Personal Use Only: The Site is strictly for your personal, non-commercial use. Unauthorized commercial use, duplication, or resale of any product or content is prohibited.',
    ],
  },
  {
    heading: '2. User Accounts & Security',
    paragraph:
      'The Site is intended for use by adults. Any minor accessing the platform should do so under parental or guardian supervision.',
    bullets: [
      'Account Responsibility: You are responsible for maintaining the confidentiality of your account credentials, password, and restricting access to your devices. All activities under your account are your sole responsibility.',
      'Termination: We reserve the right to refuse service, terminate accounts, or cancel orders at our sole discretion if these Terms are violated.',
    ],
  },
  {
    heading: '3. Orders, Pricing & Payments',
    bullets: [
      'Order Placement: Placing an order constitutes an offer to buy. Drishti Fashions or our sellers retain the right to accept or cancel any order (including orders exceeding typical individual consumption limits) at our discretion.',
      'Pricing Accuracy: While we strive for accuracy, pricing or informational errors may occur. If a product is listed at an incorrect price, we reserve the right to cancel the order and issue a full refund.',
      'Payment Modes: Payments can be made via Credit Cards, Debit Cards, Net Banking, Wallets, UPI, Cash on Delivery (COD), and gift cards.',
    ],
  },
  {
    heading: '4. Intellectual Property Rights',
    paragraph:
      'All content on this Site—including the Drishti Fashions name, logos, text, designs, graphics, icons, images, audio clips, and software—is the exclusive property of DRISTI DHAMHI VYAPAAR PRIVATE LIMITED or its licensors and is protected by Indian copyright and trademark laws.',
    bullets: [
      'Restrictions: You may not copy, reproduce, distribute, republish, download, or modify any content from the Site without explicit written permission, except for your personal, non-commercial viewing.',
    ],
  },
  {
    heading: '5. Limitation of Liability & Disclaimers',
    paragraph:
      'The Site and its contents are provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, either express or implied. Drishti Fashions, its directors, employees, or affiliates shall not be liable for any indirect, incidental, punitive, or consequential damages arising from your use of the Site, product delays, or third-party actions.',
  },
  {
    heading: '6. Governing Law & Dispute Resolution',
    bullets: [
      'Jurisdiction: These Terms & Conditions are governed by and construed in accordance with the laws of India. Any legal proceedings shall be subject to the exclusive jurisdiction of the courts in Kolkata, West Bengal.',
      'Arbitration: Any disputes arising out of these Terms shall be referred to an independent arbitrator appointed mutually, in accordance with the Arbitration and Conciliation Act, 1996, with the seat of arbitration in Kolkata.',
    ],
  },
];

export const TermsConditionsPage: React.FC<TermsConditionsPageProps> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen max-w-4xl mx-auto px-4 py-8 space-y-8">
      <button
        onClick={() => onNavigate('/')}
        className="inline-flex items-center gap-2 text-xs font-bold text-[#0d1648] hover:text-[#755b00]"
      >
        <ArrowLeft className="w-4 h-4" /> Back to Home
      </button>

      <div className="text-center space-y-3 pb-4">
        <div className="flex justify-center mb-2">
          <Scale className="w-10 h-10 text-[#755b00]" />
        </div>
        <h1 className="font-serif text-3xl font-bold text-[#0d1648]">Terms & Conditions</h1>
        <p className="text-xs text-[#767680] font-sans max-w-2xl mx-auto leading-relaxed">
          Welcome to Drishti Fashions (the "Site" or "Application"). By accessing, browsing, or shopping on our
          platform, you acknowledge and agree to be bound by these Terms & Conditions, along with our Privacy Policy
          and Shipping & Return Policies (collectively, the "Policies").
        </p>
      </div>

      <div className="bg-white rounded-2xl p-6 sm:p-10 shadow-lg border border-[#c6c5d0]/30 space-y-8 text-xs font-sans leading-relaxed text-[#46464f]">
        {SECTIONS.map(s => (
          <section key={s.heading} className="space-y-2">
            <h2 className="font-serif text-xl font-bold text-[#0d1648]">{s.heading}</h2>
            {s.paragraph && <p>{s.paragraph}</p>}
            {s.bullets && (
              <ul className="list-disc list-inside space-y-1.5 pl-2">
                {s.bullets.map(b => (
                  <li key={b}>{b}</li>
                ))}
              </ul>
            )}
          </section>
        ))}

        <div className="bg-[#f4f2ff] rounded-xl border border-[#c6c5d0]/40 p-6 space-y-3 mt-4">
          <h3 className="font-serif text-lg font-bold text-[#0d1648]">Contact Information</h3>
          <p className="text-[#46464f]">
            If you have any questions or concerns regarding these Terms & Conditions, please reach out to our Customer
            Service Desk:
          </p>
          <div className="space-y-2">
            <p className="flex items-start gap-2">
              <FileText className="w-4 h-4 shrink-0 text-[#755b00] mt-0.5" />
              <span>
                <strong>Name:</strong> Mr. Prakash <span className="text-[#767680]">— Designation:</span> Operations Head
              </span>
            </p>
            <p className="flex items-start gap-2">
              <Gavel className="w-4 h-4 shrink-0 text-[#755b00] mt-0.5" />
              <span>
                <strong>Email:</strong>{' '}
                <a href="mailto:info@drishtifashions.com" className="text-[#755b00] hover:underline">
                  info@drishtifashions.com
                </a>
              </span>
            </p>
            <p className="flex items-start gap-2">
              <Phone className="w-4 h-4 shrink-0 text-[#755b00] mt-0.5" />
              <span>
                <strong>Phone:</strong> +91 6290486090 (Monday to Saturday, 10:00 AM to 7:00 PM)
              </span>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};